<?php
$plugin = array(
  'title'     => t('Frontera Standard Content'),
  'theme'     => 'frontera_standard_content',
  'icon'      => 'frontera_standard_content.png',
  'admin css' => '../../../css/frontera_omega.layouts.css',
  'category'  => 'Frontera',
  'regions' => array(
    'image'             => t('Image'),
    'summary'           => t('Summary'),
    'details'           => t('Details'),
    'complementary'   => t('Complementary'),
  ),
);
