<?php
$plugin = array(
  'title'     => t('Frontera Site Template'),
  'theme'     => 'frontera_site_template',
  'icon'      => 'frontera_site_template.png',
  'admin css' => '../../../css/frontera_omega.layouts.css',
  'category'  => 'Frontera',
  'regions' => array(
    'utility'           => t('Utility'),
    'branding'          => t('Branding'),
    'navigation'        => t('Navigation'),
    'help'              => t('Help'),
    'content'           => t('Main content'),
    'footer'            => t('Footer'),
  ),
);
